### PR TITLE
Fix issue where unable to select options with apostrophes. (Issue #53)

### PR DESCRIPTION
**Pull request by AndrewDRX**

### CODE REVIEW

**Comment by Calak** [comment]
Look at my comment on your issue please.

**Comment by Calak** [comment]
Your fix let two problems unsolved: 
1. When many single-quotes in a key/group, only the first one is escaped
2. When single-quote is already escaped in the string, you add one more backslash, letting it as a doubly-escaped single-quote (giving an unescaped quote).

More on that in the referenced issue #53

**Comment by AndrewDRX** [comment]
@Calak Sorry. Mistakenly closed out this pull request. Pull request #55 replaces this one, and I made your suggested changes.

**Comment by Calak** [comment]
We maybe need to investigate more to be sure that we don't forgot some edge cases over.

**Pull request closed without merging**
