### PR TITLE
Fix for issue #52

### PR DESCRIPTION
**Pull request by Calak**

### CODE REVIEW

**Comment by SamBrishes** [comment]
✔️

**Comment by Calak** [comment]
Damn, don't commited my change that fixes #65. I'll do it.

**Comment by Calak** [comment]
I'm not at home but you have to remove `s ||` from both conditions (in `set()` and `add()`) to automatically select the last added selected on single-select.

Didn't fully tested all edge case, but it should do the job.

Another thing @SamBrishes, can you explains me exactly (in details) what you're testing in the following piece of code

            if(opt.selected && con.deselect && (!opt.hasAttribute("selected") || con.multiLimit == 0)){
                opt.selected = false;
                opt.parentElement.selectedIndex = -1;
            }

**Comment by SamBrishes** [comment]
Thanks, I wasn't at home either, but now I'm. I'll check it out.

This code allows to deselect the pre-selected option by the browser by checking if the option is selected without an `selected` attribute. This can also be forced by the user setting `multiLimit` to `0`. If that is true it will set the selection index to -1, which results in the following on the source select field:

select

Sincerely,
Sam.

**Comment by Calak** [comment]
Purpose of `multiLimit: 0` is to completely disallow all selection, right? So you didn't have to check the `deselect` flag.
Also, instead of the `deselect` flag, you might use a new flag, called like `preventBrowserDefaultSelection` (or whatever) because here's nothing to do with user deselection. 
If the user want to have a cleared select at beginning but don't want to allow poeple deselecting selected options, it can be achieved easily by setting this new flag to true, and `deselect` to false. More generally the `deselect` flag should be keeped for **user interactions** (IMHO).

That's lead to a new comdition:

        if(opt.selected && ((opt.preventBrowserDefaultSelection && !opt.hasAttribute("selected")) || con.multiLimit == 0)){
            opt.selected = false;
            opt.parentElement.selectedIndex = -1;
        }

**Pull request merged**
